// ViewDigest - YouTube 자막(Transcript) 추출 유틸리티
//
// Lilys AI와 동일한 방식: 영상을 통째로 Gemini에 보내는 대신, YouTube가
// 제공하는 자막(수동 업로드 또는 자동 생성) 텍스트를 먼저 추출해 LLM에게는
// 텍스트만 전달한다. 자막이 없는 영상만 예외적으로 영상 자체를 Gemini에
// 보내는 방식(utils/gemini.js의 fileData 경로)으로 대체한다.
//
// background.js(service worker)에는 DOMParser가 없으므로, 영상 페이지 HTML과
// 자막 XML을 모두 정규식으로 직접 파싱한다(utils/channels.js와 동일한 방식).
// 로그인/API 키 없이 공개적으로 접근 가능한 엔드포인트만 사용한다.

function decodeHtmlEntities(text) {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}

function extractVideoId(url) {
  try {
    const parsed = new URL(url);
    if (parsed.hostname.includes("youtu.be")) {
      return parsed.pathname.slice(1) || null;
    }
    return parsed.searchParams.get("v");
  } catch {
    return null;
  }
}

/**
 * `"key":[ ... ]` 형태로 HTML/JS 안에 박혀 있는 JSON 배열을, 괄호 깊이를 세어
 * 그대로 잘라낸다. 정규식만으로는 배열 안에 중첩된 `[`/`]`가 있을 때
 * 잘못 잘릴 수 있어, 문자 단위로 짝을 맞춘다.
 */
function extractJsonArrayAfter(html, key) {
  const marker = `"${key}":`;
  const keyIndex = html.indexOf(marker);
  if (keyIndex === -1) return null;

  const start = html.indexOf("[", keyIndex);
  if (start === -1) return null;

  let depth = 0;
  for (let i = start; i < html.length; i++) {
    if (html[i] === "[") depth++;
    else if (html[i] === "]") {
      depth--;
      if (depth === 0) return html.slice(start, i + 1);
    }
  }
  return null;
}

/**
 * ytInitialPlayerResponse에 포함된 captionTracks 목록을 조회한다.
 * 자막이 아예 없는 영상이면 빈 배열을 반환한다.
 */
function parseCaptionTracks(html) {
  const json = extractJsonArrayAfter(html, "captionTracks");
  if (!json) return [];

  let rawTracks;
  try {
    rawTracks = JSON.parse(json);
  } catch {
    return [];
  }

  return rawTracks
    .map((track) => ({
      baseUrl: typeof track.baseUrl === "string" ? track.baseUrl : null,
      languageCode: track.languageCode ?? "",
      isAutoGenerated: track.kind === "asr",
    }))
    .filter((track) => track.baseUrl);
}

/**
 * 여러 자막 트랙 중 하나를 고른다. 한국어/영어의 수동 업로드 자막을 가장
 * 우선하고, 없으면 자동 생성 자막이라도 사용한다(그래도 없는 것보다 낫다).
 */
function pickBestTrack(tracks) {
  if (tracks.length === 0) return null;
  const find = (predicate) => tracks.find(predicate);
  return (
    find((t) => t.languageCode === "ko" && !t.isAutoGenerated) ??
    find((t) => t.languageCode === "en" && !t.isAutoGenerated) ??
    find((t) => t.languageCode === "ko") ??
    find((t) => t.languageCode === "en") ??
    tracks[0]
  );
}

function parseCaptionXml(xml) {
  const entries = [];
  const blocks = xml.match(/<text[^>]*>[\s\S]*?<\/text>/g) ?? [];

  for (const block of blocks) {
    const startMatch = block.match(/start="([\d.]+)"/);
    const textMatch = block.match(/<text[^>]*>([\s\S]*?)<\/text>/);
    if (!startMatch || !textMatch) continue;

    const text = decodeHtmlEntities(textMatch[1])
      .replace(/<[^>]+>/g, "")
      .replace(/\s+/g, " ")
      .trim();
    if (!text) continue;

    entries.push({ start: parseFloat(startMatch[1]), text });
  }

  return entries;
}

function formatTimestamp(totalSeconds) {
  const total = Math.max(0, Math.floor(totalSeconds));
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  const mm = String(m).padStart(2, "0");
  const ss = String(s).padStart(2, "0");
  return h > 0 ? `${h}:${mm}:${ss}` : `${mm}:${ss}`;
}

function formatTranscript(entries) {
  return entries.map((e) => `[${formatTimestamp(e.start)}] ${e.text}`).join("\n");
}

/**
 * YouTube 영상의 자막을 조회한다. 자막이 없거나(예: 자막을 아예 안 만든
 * 영상), 페이지/자막 요청이 실패하면 null을 반환한다 — 호출부는 이 경우
 * Gemini의 영상 이해(fileData) 경로로 폴백해야 한다.
 *
 * @param {string} youtubeUrl
 * @returns {Promise<{text: string, languageCode: string, isAutoGenerated: boolean} | null>}
 */
async function getTranscript(youtubeUrl) {
  const videoId = extractVideoId(youtubeUrl);
  if (!videoId) return null;

  const pageResponse = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
    credentials: "omit",
    headers: { "Accept-Language": "ko-KR,ko;q=0.9,en;q=0.8" },
  });
  if (!pageResponse.ok) return null;
  const html = await pageResponse.text();

  const track = pickBestTrack(parseCaptionTracks(html));
  if (!track) return null;

  const captionResponse = await fetch(track.baseUrl, { credentials: "omit" });
  if (!captionResponse.ok) return null;
  const xml = await captionResponse.text();

  const entries = parseCaptionXml(xml);
  if (entries.length === 0) return null;

  return {
    text: formatTranscript(entries),
    languageCode: track.languageCode,
    isAutoGenerated: track.isAutoGenerated,
  };
}

export { getTranscript };
