// ViewDigest - YouTube 자막(Transcript) 추출 유틸리티
//
// Lilys AI와 동일한 방식: 영상을 통째로 Gemini에 보내는 대신, YouTube가
// 제공하는 자막(수동 업로드 또는 자동 생성) 텍스트를 먼저 추출해 LLM에게는
// 텍스트만 전달한다. 자막이 없는 영상만 예외적으로 영상 자체를 Gemini에
// 보내는 방식(utils/gemini.js의 fileData 경로)으로 대체한다.
//
// background.js(service worker)에는 DOMParser가 없으므로, 영상 페이지 HTML과
// 자막 XML을 모두 정규식으로 직접 파싱한다(utils/channels.js와 동일한 방식).
// 로그인/API 키 없이 공개적으로 접근 가능한 엔드포인트만 사용한다.

function decodeHtmlEntities(text) {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}

function extractVideoId(url) {
  try {
    const parsed = new URL(url);
    if (parsed.hostname.includes("youtu.be")) {
      return parsed.pathname.slice(1) || null;
    }
    return parsed.searchParams.get("v");
  } catch {
    return null;
  }
}

/**
 * `"key":[ ... ]` 형태로 HTML/JS 안에 박혀 있는 JSON 배열을, 괄호 깊이를 세어
 * 그대로 잘라낸다. 정규식만으로는 배열 안에 중첩된 `[`/`]`가 있을 때
 * 잘못 잘릴 수 있어, 문자 단위로 짝을 맞춘다.
 *
 * 문자열 내부는 반드시 건너뛰어야 한다. 자막 트랙 이름에는 "English
 * [auto-generated]", "한국어 [자동 생성]"처럼 대괄호가 흔히 들어있어서, 따옴표를
 * 무시하고 세면 그 `]`가 배열을 조기에 끝내버린다. 그러면 잘린 JSON이 파싱에
 * 실패하고 호출부는 "자막 없음"으로 오판해 불필요하게 영상 인식 경로로 넘어간다.
 */
function extractJsonArrayAfter(html, key) {
  const marker = `"${key}":`;
  const keyIndex = html.indexOf(marker);
  if (keyIndex === -1) return null;

  const start = html.indexOf("[", keyIndex);
  if (start === -1) return null;

  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let i = start; i < html.length; i++) {
    const char = html[i];

    if (inString) {
      if (escaped) escaped = false;
      else if (char === "\\") escaped = true;
      else if (char === '"') inString = false;
      continue;
    }

    if (char === '"') inString = true;
    else if (char === "[") depth++;
    else if (char === "]") {
      depth--;
      if (depth === 0) return html.slice(start, i + 1);
    }
  }
  return null;
}

/**
 * ytInitialPlayerResponse에 포함된 captionTracks 목록을 조회한다.
 * 자막이 아예 없는 영상이면 빈 배열을 반환한다.
 */
function parseCaptionTracks(html) {
  const json = extractJsonArrayAfter(html, "captionTracks");
  if (!json) return [];

  let rawTracks;
  try {
    rawTracks = JSON.parse(json);
  } catch {
    return [];
  }

  return rawTracks
    .map((track) => ({
      baseUrl: typeof track.baseUrl === "string" ? track.baseUrl : null,
      languageCode: track.languageCode ?? "",
      isAutoGenerated: track.kind === "asr",
    }))
    .filter((track) => track.baseUrl);
}

/**
 * 여러 자막 트랙 중 하나를 고른다. 한국어/영어의 수동 업로드 자막을 가장
 * 우선하고, 없으면 자동 생성 자막이라도 사용한다(그래도 없는 것보다 낫다).
 */
function pickBestTrack(tracks) {
  if (tracks.length === 0) return null;
  const find = (predicate) => tracks.find(predicate);
  return (
    find((t) => t.languageCode === "ko" && !t.isAutoGenerated) ??
    find((t) => t.languageCode === "en" && !t.isAutoGenerated) ??
    find((t) => t.languageCode === "ko") ??
    find((t) => t.languageCode === "en") ??
    tracks[0]
  );
}

/**
 * 자막 추출이 실패한 지점을 콘솔에 남기고 null을 반환한다. 예전에는 여섯 군데가
 * 모두 맨 null을 돌려줘서, 정말 자막이 없는 영상인지 파싱/요청이 깨진 것인지
 * 구분할 방법이 없었다(그 사이 호출부는 조용히 영상 인식 경로로 넘어간다).
 */
function abort(step, detail) {
  console.warn(`[ViewDigest] 자막을 사용하지 못했습니다 — ${step}`, detail ?? "");
  return null;
}

/**
 * timedtext 응답을 json3 형식으로 요청하기 위해 fmt 파라미터를 교체한다.
 */
function withCaptionFormat(baseUrl, format) {
  try {
    const url = new URL(baseUrl);
    url.searchParams.set("fmt", format);
    return url.toString();
  } catch {
    return null;
  }
}

function parseCaptionJson3(body) {
  let data;
  try {
    data = JSON.parse(body);
  } catch {
    return [];
  }

  const entries = [];
  for (const event of data?.events ?? []) {
    const text = (event.segs ?? [])
      .map((seg) => seg.utf8 ?? "")
      .join("")
      .replace(/\s+/g, " ")
      .trim();
    if (!text) continue;
    entries.push({ start: (event.tStartMs ?? 0) / 1000, text });
  }
  return entries;
}

function parseCaptionXml(xml) {
  const entries = [];
  const blocks = xml.match(/<text[^>]*>[\s\S]*?<\/text>/g) ?? [];

  for (const block of blocks) {
    const startMatch = block.match(/start="([\d.]+)"/);
    const textMatch = block.match(/<text[^>]*>([\s\S]*?)<\/text>/);
    if (!startMatch || !textMatch) continue;

    const text = decodeHtmlEntities(textMatch[1])
      .replace(/<[^>]+>/g, "")
      .replace(/\s+/g, " ")
      .trim();
    if (!text) continue;

    entries.push({ start: parseFloat(startMatch[1]), text });
  }

  return entries;
}

function formatTimestamp(totalSeconds) {
  const total = Math.max(0, Math.floor(totalSeconds));
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  const mm = String(m).padStart(2, "0");
  const ss = String(s).padStart(2, "0");
  return h > 0 ? `${h}:${mm}:${ss}` : `${mm}:${ss}`;
}

function formatTranscript(entries) {
  return entries.map((e) => `[${formatTimestamp(e.start)}] ${e.text}`).join("\n");
}

/**
 * YouTube 영상의 자막을 조회한다. 자막이 없거나(예: 자막을 아예 안 만든
 * 영상), 페이지/자막 요청이 실패하면 null을 반환한다 — 호출부는 이 경우
 * Gemini의 영상 이해(fileData) 경로로 폴백해야 한다.
 *
 * @param {string} youtubeUrl
 * @returns {Promise<{text: string, languageCode: string, isAutoGenerated: boolean} | null>}
 */
/**
 * 포맷을 지정하지 않으면 timedtext가 200과 함께 빈 본문을 돌려주는 경우가 있어,
 * 최신 형식(json3)을 먼저 쓰고 레거시 XML로 물러선다.
 */
function captionFormats(baseUrl) {
  return [
    { label: "json3", url: withCaptionFormat(baseUrl, "json3"), parse: parseCaptionJson3 },
    { label: "xml", url: baseUrl, parse: parseCaptionXml },
  ];
}

/**
 * 주어진 요청 함수로 자막 본문을 받아 항목으로 파싱한다. 어느 경로로 받아오든
 * (페이지 안 / 확장에서 직접) 포맷 선택·파싱·실패 기록은 동일하므로 여기로 모은다.
 *
 * @param {(url: string) => Promise<{ok?: boolean, status?: number, body?: string, error?: string}>} request
 * @param {string[]} log 시도별 결과가 누적되는 배열
 */
async function readCaptionEntries(baseUrl, sourceLabel, request, log) {
  for (const { label, url, parse } of captionFormats(baseUrl)) {
    if (!url) continue;
    const attempt = `${sourceLabel}/${label}`;

    const result = await request(url);

    if (result?.error) {
      log.push(`${attempt}: 요청 실패 (${result.error})`);
      continue;
    }
    if (!result?.ok) {
      log.push(`${attempt}: HTTP ${result?.status ?? "응답 없음"}`);
      continue;
    }

    const body = result.body ?? "";
    if (!body.trim()) {
      log.push(`${attempt}: HTTP 200이지만 본문이 비어 있음`);
      continue;
    }

    const entries = parse(body);
    if (entries.length === 0) {
      log.push(`${attempt}: 본문 ${body.length}자를 받았으나 자막 항목 0개`);
      continue;
    }

    return entries;
  }
  return [];
}

function requestFromExtension(credentials) {
  return async (url) => {
    try {
      const response = await fetch(url, { credentials });
      return { ok: response.ok, status: response.status, body: await response.text() };
    } catch (error) {
      return { error: error?.message ?? String(error) };
    }
  };
}

function requestFromTab(tabId) {
  return async (url) => {
    try {
      const response = await chrome.tabs.sendMessage(tabId, { action: "fetchCaptionBody", url });
      return response ?? { error: "content script가 응답하지 않았습니다." };
    } catch (error) {
      return { error: error?.message ?? String(error) };
    }
  };
}

/**
 * 해당 영상이 열려 있는 YouTube 탭을 찾는다. 분석 버튼은 그 탭에서 눌리므로
 * 보통은 존재하지만, 채널 자동 분석처럼 탭 없이 도는 경우에는 없다.
 */
async function findWatchTab(videoId) {
  if (!globalThis.chrome?.tabs?.query) return null;

  try {
    const tabs = await chrome.tabs.query({ url: ["*://www.youtube.com/watch*", "*://m.youtube.com/watch*"] });
    return tabs.find((tab) => tab.url && extractVideoId(tab.url) === videoId) ?? null;
  } catch {
    return null;
  }
}

/**
 * 1순위 경로: 사용자가 실제로 보고 있는 YouTube 탭 안에서 자막을 가져온다.
 * timedtext URL은 그것을 발급한 세션에 묶여 있어, 그 페이지에서 읽고 그 페이지에서
 * 요청해야 본문이 온다.
 */
async function getTranscriptFromTab(videoId, log) {
  const tab = await findWatchTab(videoId);
  if (!tab) {
    log.push("페이지: 해당 영상이 열려 있는 YouTube 탭이 없습니다.");
    return null;
  }

  let slice;
  try {
    slice = await chrome.tabs.sendMessage(tab.id, { action: "readCaptionTracks" });
  } catch (error) {
    log.push(`페이지: content script를 호출하지 못했습니다 (${error?.message ?? error})`);
    return null;
  }

  if (!slice?.html) {
    log.push(`페이지: ${slice?.reason ?? "자막 트랙 목록을 받지 못했습니다."}`);
    return null;
  }

  const track = pickBestTrack(parseCaptionTracks(slice.html));
  if (!track) {
    log.push("페이지: 받아온 목록에서 자막 트랙을 파싱하지 못했습니다.");
    return null;
  }

  const entries = await readCaptionEntries(track.baseUrl, "페이지", requestFromTab(tab.id), log);
  return entries.length > 0 ? buildTranscript(entries, track) : null;
}

/**
 * 2순위 경로: 확장 페이지에서 직접 영상 페이지와 자막을 받아온다. 탭이 없을 때
 * (채널 자동 분석 등) 쓰이며, YouTube가 세션이 다른 요청을 막으면 실패할 수 있다.
 */
async function getTranscriptFromExtension(videoId, log) {
  let pageResponse;
  try {
    pageResponse = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
      credentials: "omit",
      headers: { "Accept-Language": "ko-KR,ko;q=0.9,en;q=0.8" },
    });
  } catch (error) {
    log.push(`직접: 영상 페이지 요청 실패 (${error?.message ?? error})`);
    return null;
  }

  if (!pageResponse.ok) {
    log.push(`직접: 영상 페이지 HTTP ${pageResponse.status}`);
    return null;
  }

  const html = await pageResponse.text();
  const track = pickBestTrack(parseCaptionTracks(html));
  if (!track) {
    log.push(
      html.includes("captionTracks")
        ? "직접: captionTracks 키는 있으나 파싱에 실패했습니다."
        : "직접: 페이지에 captionTracks 자체가 없습니다(자막 없는 영상이거나 축소된 페이지)."
    );
    return null;
  }

  const entries = await readCaptionEntries(track.baseUrl, "직접", requestFromExtension("omit"), log);
  return entries.length > 0 ? buildTranscript(entries, track) : null;
}

function buildTranscript(entries, track) {
  return {
    text: formatTranscript(entries),
    languageCode: track.languageCode,
    isAutoGenerated: track.isAutoGenerated,
  };
}

async function getTranscript(youtubeUrl) {
  const videoId = extractVideoId(youtubeUrl);
  if (!videoId) return abort("영상 URL에서 videoId를 찾지 못했습니다.", youtubeUrl);

  const log = [];

  const fromTab = await getTranscriptFromTab(videoId, log);
  if (fromTab) return fromTab;

  const fromExtension = await getTranscriptFromExtension(videoId, log);
  if (fromExtension) return fromExtension;

  return abort("자막을 받아오지 못했습니다.", { 시도별결과: log });
}

export { getTranscript };
