// ViewDigest - YouTube 자막(Transcript) 추출 유틸리티
//
// Lilys AI와 동일한 방식: 영상을 통째로 Gemini에 보내는 대신, YouTube가
// 제공하는 자막(수동 업로드 또는 자동 생성) 텍스트를 먼저 추출해 LLM에게는
// 텍스트만 전달한다. 자막이 없는 영상만 예외적으로 영상 자체를 Gemini에
// 보내는 방식(utils/gemini.js의 fileData 경로)으로 대체한다.
//
// background.js(service worker)에는 DOMParser가 없으므로, 영상 페이지 HTML과
// 자막 XML을 모두 정규식으로 직접 파싱한다(utils/channels.js와 동일한 방식).
// 로그인/API 키 없이 공개적으로 접근 가능한 엔드포인트만 사용한다.

function decodeHtmlEntities(text) {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}

function extractVideoId(url) {
  try {
    const parsed = new URL(url);
    if (parsed.hostname.includes("youtu.be")) {
      return parsed.pathname.slice(1) || null;
    }
    return parsed.searchParams.get("v");
  } catch {
    return null;
  }
}

/**
 * `"key":[ ... ]` 형태로 HTML/JS 안에 박혀 있는 JSON 배열을, 괄호 깊이를 세어
 * 그대로 잘라낸다. 정규식만으로는 배열 안에 중첩된 `[`/`]`가 있을 때
 * 잘못 잘릴 수 있어, 문자 단위로 짝을 맞춘다.
 *
 * 문자열 내부는 반드시 건너뛰어야 한다. 자막 트랙 이름에는 "English
 * [auto-generated]", "한국어 [자동 생성]"처럼 대괄호가 흔히 들어있어서, 따옴표를
 * 무시하고 세면 그 `]`가 배열을 조기에 끝내버린다. 그러면 잘린 JSON이 파싱에
 * 실패하고 호출부는 "자막 없음"으로 오판해 불필요하게 영상 인식 경로로 넘어간다.
 */
function extractJsonArrayAfter(html, key) {
  const marker = `"${key}":`;
  const keyIndex = html.indexOf(marker);
  if (keyIndex === -1) return null;

  const start = html.indexOf("[", keyIndex);
  if (start === -1) return null;

  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let i = start; i < html.length; i++) {
    const char = html[i];

    if (inString) {
      if (escaped) escaped = false;
      else if (char === "\\") escaped = true;
      else if (char === '"') inString = false;
      continue;
    }

    if (char === '"') inString = true;
    else if (char === "[") depth++;
    else if (char === "]") {
      depth--;
      if (depth === 0) return html.slice(start, i + 1);
    }
  }
  return null;
}

/**
 * ytInitialPlayerResponse에 포함된 captionTracks 목록을 조회한다.
 * 자막이 아예 없는 영상이면 빈 배열을 반환한다.
 */
function parseCaptionTracks(html) {
  const json = extractJsonArrayAfter(html, "captionTracks");
  if (!json) return [];

  let rawTracks;
  try {
    rawTracks = JSON.parse(json);
  } catch {
    return [];
  }

  return rawTracks
    .map((track) => ({
      baseUrl: typeof track.baseUrl === "string" ? track.baseUrl : null,
      languageCode: track.languageCode ?? "",
      isAutoGenerated: track.kind === "asr",
    }))
    .filter((track) => track.baseUrl);
}

/**
 * 여러 자막 트랙 중 하나를 고른다. 한국어/영어의 수동 업로드 자막을 가장
 * 우선하고, 없으면 자동 생성 자막이라도 사용한다(그래도 없는 것보다 낫다).
 */
function pickBestTrack(tracks) {
  if (tracks.length === 0) return null;
  const find = (predicate) => tracks.find(predicate);
  return (
    find((t) => t.languageCode === "ko" && !t.isAutoGenerated) ??
    find((t) => t.languageCode === "en" && !t.isAutoGenerated) ??
    find((t) => t.languageCode === "ko") ??
    find((t) => t.languageCode === "en") ??
    tracks[0]
  );
}

/**
 * 자막 추출이 실패한 지점을 콘솔에 남기고 null을 반환한다. 예전에는 여섯 군데가
 * 모두 맨 null을 돌려줘서, 정말 자막이 없는 영상인지 파싱/요청이 깨진 것인지
 * 구분할 방법이 없었다(그 사이 호출부는 조용히 영상 인식 경로로 넘어간다).
 */
function abort(step, detail) {
  console.warn(`[ViewDigest] 자막을 사용하지 못했습니다 — ${step}`, detail ?? "");
  return null;
}

/**
 * timedtext 응답을 json3 형식으로 요청하기 위해 fmt 파라미터를 교체한다.
 */
function withCaptionFormat(baseUrl, format) {
  try {
    const url = new URL(baseUrl);
    url.searchParams.set("fmt", format);
    return url.toString();
  } catch {
    return null;
  }
}

function parseCaptionJson3(body) {
  let data;
  try {
    data = JSON.parse(body);
  } catch {
    return [];
  }

  const entries = [];
  for (const event of data?.events ?? []) {
    const text = (event.segs ?? [])
      .map((seg) => seg.utf8 ?? "")
      .join("")
      .replace(/\s+/g, " ")
      .trim();
    if (!text) continue;
    entries.push({ start: (event.tStartMs ?? 0) / 1000, text });
  }
  return entries;
}

function parseCaptionXml(xml) {
  const entries = [];
  const blocks = xml.match(/<text[^>]*>[\s\S]*?<\/text>/g) ?? [];

  for (const block of blocks) {
    const startMatch = block.match(/start="([\d.]+)"/);
    const textMatch = block.match(/<text[^>]*>([\s\S]*?)<\/text>/);
    if (!startMatch || !textMatch) continue;

    const text = decodeHtmlEntities(textMatch[1])
      .replace(/<[^>]+>/g, "")
      .replace(/\s+/g, " ")
      .trim();
    if (!text) continue;

    entries.push({ start: parseFloat(startMatch[1]), text });
  }

  return entries;
}

function formatTimestamp(totalSeconds) {
  const total = Math.max(0, Math.floor(totalSeconds));
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  const mm = String(m).padStart(2, "0");
  const ss = String(s).padStart(2, "0");
  return h > 0 ? `${h}:${mm}:${ss}` : `${mm}:${ss}`;
}

function formatTranscript(entries) {
  return entries.map((e) => `[${formatTimestamp(e.start)}] ${e.text}`).join("\n");
}

/**
 * YouTube 영상의 자막을 조회한다. 자막이 없거나(예: 자막을 아예 안 만든
 * 영상), 페이지/자막 요청이 실패하면 null을 반환한다 — 호출부는 이 경우
 * Gemini의 영상 이해(fileData) 경로로 폴백해야 한다.
 *
 * @param {string} youtubeUrl
 * @returns {Promise<{text: string, languageCode: string, isAutoGenerated: boolean} | null>}
 */
async function fetchCaptionEntries(baseUrl) {
  // 포맷을 지정하지 않으면 timedtext가 200과 함께 빈 본문을 돌려주는 경우가 있어,
  // 최신 형식(json3)을 먼저 시도하고 레거시 XML로 물러선다.
  const attempts = [
    { url: withCaptionFormat(baseUrl, "json3"), parse: parseCaptionJson3 },
    { url: baseUrl, parse: parseCaptionXml },
  ];

  for (const { url, parse } of attempts) {
    if (!url) continue;

    const response = await fetch(url, { credentials: "omit" });
    if (!response.ok) continue;

    const body = await response.text();
    if (!body.trim()) continue;

    const entries = parse(body);
    if (entries.length > 0) return entries;
  }
  return [];
}

async function getTranscript(youtubeUrl) {
  const videoId = extractVideoId(youtubeUrl);
  if (!videoId) return abort("영상 URL에서 videoId를 찾지 못했습니다.", youtubeUrl);

  const pageResponse = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
    credentials: "omit",
    headers: { "Accept-Language": "ko-KR,ko;q=0.9,en;q=0.8" },
  });
  if (!pageResponse.ok) {
    return abort("영상 페이지를 불러오지 못했습니다.", `HTTP ${pageResponse.status}`);
  }
  const html = await pageResponse.text();

  const tracks = parseCaptionTracks(html);
  if (tracks.length === 0) {
    // 페이지는 받았는데 트랙이 하나도 없다면, 정말 자막이 없는 영상일 수도 있고
    // YouTube가 자막 정보가 빠진 페이지를 내려준 것일 수도 있어 둘을 구분해둔다.
    return abort(
      "영상 페이지에서 자막 트랙 목록을 찾지 못했습니다.",
      html.includes("captionTracks")
        ? "captionTracks 키는 있으나 파싱에 실패했습니다."
        : "페이지에 captionTracks 자체가 없습니다(자막 없는 영상이거나 축소된 페이지)."
    );
  }

  const track = pickBestTrack(tracks);
  const entries = await fetchCaptionEntries(track.baseUrl);
  if (entries.length === 0) {
    return abort("자막 트랙은 찾았지만 내용을 받아오지 못했습니다.", track.baseUrl);
  }

  return {
    text: formatTranscript(entries),
    languageCode: track.languageCode,
    isAutoGenerated: track.isAutoGenerated,
  };
}

export { getTranscript };
